#!/usr/bin/env python3
"""
Generate placeholder pixel-art sprites for the RPG demo's migration from
emoji to PNG.

ASCII grids → PNG strips (or single frames) written under
`public/sprites/<folder>/<id>.png`. These are hand-authored chunky
placeholders; replace with proper art when an artist is on board. The
shapes only need to be unambiguous silhouettes — the `image-rendering:
pixelated` rule plus the CSS idle loop do the rest.

Run:  python3 scripts/generate-sprites.py
"""
from __future__ import annotations

import struct
import zlib
from pathlib import Path

# Endesga-style palette. Add a key here when you need a new colour.
PALETTE: dict[str, tuple[int, int, int, int]] = {
    '.': (0, 0, 0, 0),            # transparent
    'k': (26, 28, 44, 255),       # near-black
    'd': (65, 66, 78, 255),       # dark gray
    'w': (244, 244, 244, 255),    # white
    'b': (218, 208, 197, 255),    # bone
    'r': (177, 62, 83, 255),      # red
    'R': (239, 125, 87, 255),     # orange
    'y': (255, 205, 117, 255),    # yellow
    'g': (167, 240, 112, 255),    # light green
    'G': (56, 183, 100, 255),     # dark green
    'n': (115, 83, 59, 255),      # brown
    'p': (124, 77, 138, 255),     # purple
    's': (224, 165, 137, 255),    # skin
    'c': (65, 166, 246, 255),     # cyan
    'B': (38, 70, 110, 255),      # deep blue
    'S': (153, 229, 80, 255),     # bright accent green
}


def to_grid(spec: str) -> list[list[str]]:
    rows = [r for r in spec.strip('\n').splitlines() if r]
    width = len(rows[0])
    grid: list[list[str]] = []
    for r in rows:
        if len(r) != width:
            raise ValueError(f'row width mismatch: {len(r)} vs {width}: {r!r}')
        grid.append(list(r))
    return grid


def write_png(path: Path, w: int, h: int, raw_rows: bytes) -> None:
    sig = b'\x89PNG\r\n\x1a\n'

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack('>I', len(data))
            + tag
            + data
            + struct.pack('>I', zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    ihdr = struct.pack('>IIBBBBB', w, h, 8, 6, 0, 0, 0)
    idat = zlib.compress(raw_rows, 9)
    path.write_bytes(sig + chunk(b'IHDR', ihdr) + chunk(b'IDAT', idat) + chunk(b'IEND', b''))


def render(out: Path, *frames: str) -> None:
    """Render one or more equally sized ASCII grids side-by-side into a PNG."""
    grids = [to_grid(f) for f in frames]
    h = len(grids[0])
    fw = len(grids[0][0])
    for g in grids[1:]:
        if len(g) != h or len(g[0]) != fw:
            raise ValueError(f'{out.name}: frame size mismatch')
    w = fw * len(grids)
    raw = bytearray()
    for y in range(h):
        raw.append(0)  # PNG row filter byte
        for x in range(w):
            grid = grids[x // fw]
            col = grid[y][x % fw]
            raw.extend(PALETTE[col])
    write_png(out, w, h, bytes(raw))


# ─── Enemies ──────────────────────────────────────────────────────────────────

SLIME_A = """
................
................
................
.....gggggg.....
....ggGgggGg....
....gGgwgwGg....
....ggGwGwGg....
....ggGGGGgg....
....gggggggg....
.....gggggg.....
................
................
................
................
................
................
"""

SLIME_B = """
................
................
................
................
.....gggggg.....
.....gGggGg.....
....ggGwgwGg....
....ggGGGGgg....
....gggggggg....
....gggggggg....
.....gggggg.....
................
................
................
................
................
"""

BAT_A = """
................
................
................
.kk.........kk..
.kkk.......kkk..
..kkk.kkkk.kk...
..kkkkwkwkkkk...
..kkkkkkkkkkk...
...kkkkkkkkkk...
....kkkkkkkk....
.....kkkkkk.....
................
................
................
................
................
"""

BAT_B = """
................
.kk.........kk..
.kkkk.....kkkk..
..kkkk...kkkk...
..kkkkkkkkkkk...
..kkkkwkwkkkk...
..kkkkkkkkkkk...
...kkkkkkkkkk...
....kkkkkkkk....
.....kkkkkk.....
................
................
................
................
................
................
"""

GOBLIN_A = """
................
.....GGGGGG.....
....GGGGGGGG....
....GwkGGwkG....
....GGGGGGGG....
....GGGGGGGG....
....rrrrrrrr....
...rrrrrrrrrr...
...rrrrrrrrrr...
....rrrrrrrr....
....nn....nn....
....nn....nn....
...GGG....GGG...
................
................
................
"""

GOBLIN_B = """
................
......GGGGGG....
.....GGGGGGGG...
.....GwkGGwkG...
.....GGGGGGGG...
....GGGGGGGG....
....rrrrrrrr....
...rrrrrrrrrr...
...rrrrrrrrrr...
....rrrrrrrr....
....nn....nn....
....nn....nn....
...GGG....GGG...
................
................
................
"""

SKELETON_A = """
................
.....bbbbbb.....
....bbbbbbbb....
....bkbbbbkb....
....bbbbbbbb....
.....bbkkbb.....
....bbbbbbbb....
...dddddddddd...
...ddwwwwwwdd...
...ddwwwwwwdd...
...dddddddddd...
....dd....dd....
....dd....dd....
...bbb....bbb...
................
................
"""

SKELETON_B = """
................
......bbbbbb....
.....bbbbbbbb...
.....bkbbbbkb...
.....bbbbbbbb...
......bbkkbb....
.....bbbbbbbb...
....dddddddddd..
....ddwwwwwwdd..
....ddwwwwwwdd..
....dddddddddd..
.....dd....dd...
.....dd....dd...
....bbb....bbb..
................
................
"""

DRAGON_A = """
........................
........................
.........rrrrrr.........
........rRRRRRRr........
.......rRRyRRyRRr.......
.......rRRkRRkRRr.......
.......rRRRRRRRRr.......
........rRRRRRRr........
.........rrrrrr.........
.........rr..rr.........
.........rr..rr.........
.........rr..rr.........
.......rrrr..rrrr.......
......rrrr....rrrr......
.....rrrr......rrrr.....
....rrrr........rrrr....
.....rrr........rrr.....
......rr........rr......
.......r........r.......
........................
.........rrrrrr.........
........rrrrrrrr........
.........rrrrrr.........
........................
"""

DRAGON_B = """
........................
.........rrrrrr.........
........rRRRRRRr........
.......rRRyRRyRRr.......
.......rRRkRRkRRr.......
.......rRRRRRRRRr.......
........rRRRRRRr........
.........rrrrrr.........
.........rr..rr.........
.........rr..rr.........
.....rrrrrr..rrrrrr.....
....rrrrr......rrrrr....
...rrrr..........rrrr...
....rrrr........rrrr....
.....rrr........rrr.....
......rr........rr......
.......r........r.......
........................
........................
.........rrrrrr.........
........rrrrrrrr........
.........rrrrrr.........
........................
........................
"""


# ─── Heroes (battle sprites) ─────────────────────────────────────────────────
# Authored at 16×16 logical pixels; the Sprite component renders at 48px
# (3× nearest-neighbour scale). Each set is a 2-frame idle: frame 0 neutral,
# frame 1 a small bob to give the figure life.

WARRIOR_A = """
................
......dddd......
.....dddddd.....
.....dwddwd.....
.....dddddd.....
......dssd......
....ddddddwd....
...drrrrrrwd....
...drryyyrrd....
....drrrrrd.....
....drrrrrd.....
.....rrrrr......
.....dd.dd......
.....dd.dd......
....ddd.ddd.....
................
"""

WARRIOR_B = """
................
................
......dddd......
.....dddddd.....
.....dwddwd.....
.....dddddd.....
......dssd......
....ddddddwd....
...drrrrrrwd....
...drryyyrrd....
....drrrrrd.....
....drrrrrd.....
.....rrrrr......
....ddd.ddd.....
................
................
"""

MAGE_A = """
................
......pppp......
.....pppppp.....
....pppppppp....
....pppwwppp....
.....pssssp....y
......dssd....y.
......dwwd...y..
.....pppppppy...
....ppppppppp...
...pppppppppp...
....pppppppp....
....pppppppp....
.....pp..pp.....
....ppp..ppp....
................
"""

MAGE_B = """
................
................
......pppp......
.....pppppp.....
....pppppppp....
....pppwwppp....
.....pssssp....y
......dssd....y.
......dwwd...y..
.....pppppppy...
....ppppppppp...
...pppppppppp...
....pppppppp....
.....pp..pp.....
....ppp..ppp....
................
"""

ROGUE_A = """
................
.....BBBB.......
....BBssBB......
....BBssBB......
....BBBBBB......
....BcBBBcB.....
...BcBBBBBcB....
...BBBBBBBBB....
...BBBkkkBBB....
....BBBBBBB.....
....BBBBBBB.....
.....BB.BB......
.....BB.BB......
....BBB.BBB.....
................
................
"""

ROGUE_B = """
................
................
.....BBBB.......
....BBssBB......
....BBssBB......
....BBBBBB......
....BcBBBcB.....
...BcBBBBBcB....
...BBBBBBBBB....
...BBBkkkBBB....
....BBBBBBB.....
....BBBBBBB.....
.....BB.BB......
....BBB.BBB.....
................
................
"""


# ─── Hero map tokens ─────────────────────────────────────────────────────────
# Single-frame, top-down-ish silhouettes. Rendered at the 16-px native token
# size — 1:1 to the source pixels.

TOKEN_WARRIOR = """
................
......dddd......
.....dddddd.....
.....dwddwd.....
.....dddddd.....
....drrrrrrd....
...drrryyrrrd...
...drrrrrrrrd...
....drrrrrrd....
.....rrrrrr.....
.....dd..dd.....
.....dd..dd.....
................
................
................
................
"""

TOKEN_MAGE = """
................
.......pp.......
......pppp......
.....pppppp.....
....pppwwppp....
....pppsspppy...
....pppppppy....
....pppppppy....
....ppppppppy...
....pppppppp....
....pppppppp....
.....pp..pp.....
.....pp..pp.....
................
................
................
"""

TOKEN_ROGUE = """
................
.....BBBB.......
....BBssBB......
....BBBBBB......
....BcBBBcB.....
...BcBBBBBcB....
...BBBBBBBBB....
...BBkBBBkBB....
....BBBBBBB.....
....BBBBBBB.....
.....BB.BB......
.....BB.BB......
................
................
................
................
"""


# ─── Map tile NPCs and boss ──────────────────────────────────────────────────

TOKEN_MERCHANT = """
................
......yyyy......
.....yyyyyy.....
....yyyyyyyy....
.....yyyyyy.....
......ssss......
.....nnnnnn.....
....nnnyynnn....
....nnnyynnny...
....nnnnnnnny...
....nnnnnnnn....
.....nn..nn.....
.....nn..nn.....
................
................
................
"""

TOKEN_HEALER = """
................
......wwww......
.....wwwwww.....
....wwwsswww....
.....wssssw.....
.....wwwwww.....
....wwwwwwww....
....wwwrwwww....
....wwrrrwww....
....wwwrwwww....
....wwwwwwww....
.....ww..ww.....
.....ww..ww.....
................
................
................
"""

# ─── Items (consumables) ─────────────────────────────────────────────────────
# Authored at 16×16; the Sprite component renders these in the 16–32px range
# depending on the surface (inventory cards vs. battle menu buttons).

ITEM_POTION = """
................
.......dd.......
......dddd......
......dnnd......
.....ddnndd.....
.....drrrrd.....
....drwrrrrd....
...drrrrrrrrd...
...drrwrrrrrd...
...drrrrrrrrd...
....drrrrrrd....
.....dddddd.....
................
................
................
................
"""

ITEM_ETHER = """
................
.......dd.......
......dddd......
......dnnd......
.....ddnndd.....
.....dccccd.....
....dcwccccd....
...dccccccccd...
...dccwccccd....
...dccccccccd...
....dccccccd....
.....dddddd.....
................
................
................
................
"""

ITEM_HERO_STONE = """
................
................
.......yy.......
......pppp......
.....pppppp.....
....pppwwppp....
....pppwwppp....
....pppppppp....
.....pppppp.....
......pppp......
.......pp.......
................
................
................
................
................
"""

ITEM_ELIXIR = """
................
......yyyy......
.......dd.......
.......dd.......
......dddd......
.....dyyyyd.....
....dywyyyyd....
...dyyyyyyyyd...
...dyywyyyyyd...
...dyyyyyyyyd...
....dyyyyyyd....
.....dddddd.....
................
................
................
................
"""


# ─── Equipment (weapons / armor / trinkets) ──────────────────────────────────
# Authored at 16×16 single frame. Rendered at 16–32px depending on surface
# (merchant gear row vs inventory card vs equipped slot).

EQUIP_BRONZE_SWORD = """
................
......dwd.......
......dwd.......
......dwd.......
......dwd.......
......dwd.......
......dwd.......
......dwd.......
......dwd.......
....nnnnnnn.....
......nnn.......
......nnn.......
......nnn.......
.....yyyyy......
......yyy.......
................
"""

EQUIP_STEEL_SWORD = """
................
......www.......
.....dwwwd......
......dwd.......
......dwd.......
......dwd.......
......dwd.......
......dwd.......
......dwd.......
....dddwddd.....
......nnn.......
......nnn.......
......nnn.......
.....wwwww......
......www.......
................
"""

EQUIP_MAGE_STAFF = """
................
......yyy.......
.....yywyy......
......yyy.......
.......y........
......nnn.......
......nwn.......
......nnn.......
......nwn.......
......nnn.......
......nwn.......
......nnn.......
......nwn.......
......nnn.......
......nnn.......
................
"""

EQUIP_ROGUE_DAGGER = """
................
................
.......w........
......www.......
.....wwwww......
......dwd.......
......dwd.......
......dwd.......
.....nnnnn......
......nnn.......
......nnn.......
.....yyyyy......
................
................
................
................
"""

EQUIP_LEATHER_VEST = """
................
................
....nn....nn....
....nnnnnnnn....
...nnnyynnnnn...
...nnnyynnnnn...
...nnnnnnnnnn...
...nnnnnnnnnn...
...nnnnnnnnnn...
...nnnnnnnnnn...
....nnnnnnnn....
....nnnnnnnn....
................
................
................
................
"""

EQUIP_CHAIN_MAIL = """
................
................
....dd....dd....
....ddddddddd...
...ddwdwdwdwdd..
...ddwdwdwdwdd..
...ddddddddddd..
...ddwdwdwdwdd..
...ddwdwdwdwdd..
...ddddddddddd..
...ddwdwdwdwdd..
....ddddddddd...
................
................
................
................
"""

EQUIP_MAGE_ROBE = """
................
......pppp......
.....pppppp.....
....pppwwppp....
....pppwwppp....
.....pppppp.....
....pppppppp....
...pppppppppp...
...ppppyypppp...
...ppppyypppp...
...pppppppppp...
...pppppppppp...
....pppppppp....
.....pp..pp.....
................
................
"""

EQUIP_VIGOR_RING = """
................
................
................
................
......rrr.......
.....yyyyy......
....yy...yy.....
....y.....y.....
....yy...yy.....
.....yyyyy......
................
................
................
................
................
................
"""

EQUIP_LUCKY_CHARM = """
................
................
......g.g.......
.....gSgSg......
.....gSSSg......
....gSSSSSg.....
....ggSSSgg.....
.....gSSSg......
......ggg.......
.......g........
.......g........
.......g........
................
................
................
................
"""

EQUIP_AEGIS_PENDANT = """
................
......yyy.......
......y.y.......
......y.y.......
.....cccccc.....
....cccccccc....
....cwcccccwc...
....cccccccc....
....cccccccc....
.....cccccc.....
......cccc......
.......cc.......
................
................
................
................
"""


# ─── Status effect icons (chip-size) ─────────────────────────────────────────
# Authored at 12×12 — these are tiny enough that we lean on clear silhouettes
# rather than detail. Rendered at 14–16px in the StatusChips component.

STATUS_POISON = """
............
.....g......
....ggg.....
....gSg.....
...ggggg....
...gSGSg....
...ggggg....
....ggg.....
.....g......
............
............
............
"""

STATUS_BURN = """
.....k......
.....y......
....yyR.....
....yRy.....
...RyyRR....
...RRyRR....
..RRRRRRR...
..RRRyRRR...
..RRRRrRR...
...RrrrR....
....rrr.....
............
"""

STATUS_STUN = """
............
....yyyyy...
...y...yy...
..y...yyy...
..y...y.....
..y..yy.....
..y..yyy....
..y...yy....
...y...y....
....yyyy....
............
............
"""

STATUS_SHIELD = """
............
...cccccc...
...cccccc...
..ccwwwwcc..
..cwwwwwwc..
..cccccccc..
..cccccccc..
..ccccccc...
...cccccc...
....cccc....
.....cc.....
............
"""


# A resting / coiled dragon — eyes closed (drawn as gaps in the head row) so
# the silhouette reads as "sleeping menace" rather than "fighting form."
TOKEN_BOSS_DRAGON = """
................
.....rrrrrr.....
....rRRRRRRr....
....RRRyyRRR....
....RRRRRRRR....
....RRRRRRRR....
.....rRRRRr.....
......rrrr......
......rrrr......
.....rrrrrr.....
....rrrrrrrr....
...rrrrrrrrrr...
....rrrrrrrr....
.....rr..rr.....
................
................
"""


# ─── Output table ────────────────────────────────────────────────────────────

SPRITES: list[tuple[str, str, tuple[str, ...]]] = [
    # (folder, filename, (frames...))
    ('enemies', 'slime.png',    (SLIME_A, SLIME_B)),
    ('enemies', 'bat.png',      (BAT_A, BAT_B)),
    ('enemies', 'goblin.png',   (GOBLIN_A, GOBLIN_B)),
    ('enemies', 'skeleton.png', (SKELETON_A, SKELETON_B)),
    ('enemies', 'dragon.png',   (DRAGON_A, DRAGON_B)),
    ('heroes',  'warrior.png',  (WARRIOR_A, WARRIOR_B)),
    ('heroes',  'mage.png',     (MAGE_A, MAGE_B)),
    ('heroes',  'rogue.png',    (ROGUE_A, ROGUE_B)),
    ('tokens',  'hero-warrior.png', (TOKEN_WARRIOR,)),
    ('tokens',  'hero-mage.png',    (TOKEN_MAGE,)),
    ('tokens',  'hero-rogue.png',   (TOKEN_ROGUE,)),
    ('tokens',  'merchant.png',     (TOKEN_MERCHANT,)),
    ('tokens',  'healer.png',       (TOKEN_HEALER,)),
    ('tokens',  'boss-dragon.png',  (TOKEN_BOSS_DRAGON,)),
    ('items',   'potion.png',       (ITEM_POTION,)),
    ('items',   'ether.png',        (ITEM_ETHER,)),
    ('items',   'hero-stone.png',   (ITEM_HERO_STONE,)),
    ('items',   'elixir.png',       (ITEM_ELIXIR,)),
    ('equipment', 'bronze-sword.png',  (EQUIP_BRONZE_SWORD,)),
    ('equipment', 'steel-sword.png',   (EQUIP_STEEL_SWORD,)),
    ('equipment', 'mage-staff.png',    (EQUIP_MAGE_STAFF,)),
    ('equipment', 'rogue-dagger.png',  (EQUIP_ROGUE_DAGGER,)),
    ('equipment', 'leather-vest.png',  (EQUIP_LEATHER_VEST,)),
    ('equipment', 'chain-mail.png',    (EQUIP_CHAIN_MAIL,)),
    ('equipment', 'mage-robe.png',     (EQUIP_MAGE_ROBE,)),
    ('equipment', 'vigor-ring.png',    (EQUIP_VIGOR_RING,)),
    ('equipment', 'lucky-charm.png',   (EQUIP_LUCKY_CHARM,)),
    ('equipment', 'aegis-pendant.png', (EQUIP_AEGIS_PENDANT,)),
    ('statuses',  'poison.png',        (STATUS_POISON,)),
    ('statuses',  'burn.png',          (STATUS_BURN,)),
    ('statuses',  'stun.png',          (STATUS_STUN,)),
    ('statuses',  'shield.png',        (STATUS_SHIELD,)),
]


def main() -> None:
    here = Path(__file__).resolve().parent.parent
    for folder, name, frames in SPRITES:
        out_dir = here / 'public' / 'sprites' / folder
        out_dir.mkdir(parents=True, exist_ok=True)
        path = out_dir / name
        render(path, *frames)
        print(f'  wrote {path.relative_to(here)} ({path.stat().st_size} bytes)')


if __name__ == '__main__':
    main()
